quark:
  useDirName: "临时存储文件"
  cookie: ""
sharesLinks:
  - link:
      url: "https://pan.quark.cn/s/787b447799dc"
      passCode: ""
localSaveDir: "music"
delay: 0.5
downloadFilter:
  include: ""
  exclude: ".jpg|.JPG"
proxy: ""