name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 监听版本标签，如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]      # 目标平台：Linux, Windows, macOS
        goarch: [amd64, arm64]              # 目标架构：amd64, arm64
        exclude:
          - goos: windows
            goarch: arm64  # Windows 不支持 arm64
        include:
          # 增加对 linux armv6 和 armv7 的支持
          - goos: linux
            goarch: armv6
          - goos: linux
            goarch: armv7

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22  # 使用的 Go 版本

      - name: Build binaries
        run: |
          output_name=QuarkDownloader-${{ matrix.goos }}-${{ matrix.goarch }}
          if [[ "${{ matrix.goos }}" == "windows" ]]; then
            output_name="${output_name}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $output_name ./cmd # 编译项目
        env:
          CGO_ENABLED: 0  # 确保生成静态链接的可执行文件

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: QuarkDownloader-${{ matrix.goos }}-${{ matrix.goarch }}
          path: QuarkDownloader-${{ matrix.goos }}-${{ matrix.goarch }}*  # 上传生成的二进制文件，考虑 Windows 的 .exe 文件

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux amd64
        uses: actions/download-artifact@v3
        with:
          name: QuarkDownloader-linux-amd64

      - name: Download Linux arm64
        uses: actions/download-artifact@v3
        with:
          name: QuarkDownloader-linux-arm64

      - name: Download Windows amd64
        uses: actions/download-artifact@v3
        with:
          name: QuarkDownloader-windows-amd64

      - name: Download macOS amd64
        uses: actions/download-artifact@v3
        with:
          name: QuarkDownloader-darwin-amd64

      - name: Download macOS arm64
        uses: actions/download-artifact@v3
        with:
          name: QuarkDownloader-darwin-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            QuarkDownloader-linux-amd64
            QuarkDownloader-linux-arm64
            QuarkDownloader-windows-amd64.exe
            QuarkDownloader-darwin-amd64
            QuarkDownloader-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 的令牌发布 Release
